let myDate=new Date()
// console.log(myDate)
// console.log(myDate.toString())
// console.log(myDate.toDateString())
// console.log(myDate.toLocaleString())

let mDate=new Date("01-12-2023")
// console.log(mDate.toLocaleString())
// console.log(mDate.getMonth()+1)
let myTime=Date.now()
console.log(myTime)